### PR TITLE
Added uid_key and email_key and linked to omniauth-cas for more options

### PR DESCRIPTION
**Pull request by bradspry**
Added uid_key and email_key to complete the puzzle. Additionally linked to omniauth-cas for more cas keys and options.

### CODE REVIEW

**Comment by mark-cooper** [comment]
@bradspry Thx for the PR. Would you mind using the default values for the examples? I think the defaults are were most people would want to start, and maybe add the values you used in a comment to the right?

I'm glad you got this working!

**Comment by bradspry** [comment]
@mark-cooper, yes, I'll gather the default values from omniauth-cas and update the pull now.

**Comment by bradspry** [comment]
All that matters is the cas_keys have been surfaced for all :+1:

**Comment by mark-cooper** [comment]
Awesome, thanks @bradspry

**Pull request merged**
