### PR TITLE
Update Gemfile

### PR DESCRIPTION
**Pull request by Geoffsc**
In order to use this plugin with ArchivesSpace 3.1.0 I had to update the addressable gem to 2.8.0.

### CODE REVIEW

**Comment by mark-cooper** [comment]
Hi @Geoffsc, thx for the PR. @Blake- you have https://github.com/lyrasis/aspace-oauth/pull/23/files - is addressable 2.8.0 compatible with previous releases of ArchivesSpace? Easiest win: if this works with aspace v2.8.1+ I'd say lets accept this PR and close yours.

**Comment by Blake-** [comment]
@Geoffsc @mark-cooper v2.8.1 is very unhappy with that

```
[2021-11-13T08:33:23-05:00] (und) WARNING: The parameter 'backend_log_level' was already set
[2021-11-13T08:33:23-05:00] (und) WARNING: The parameter 'indexer_records_per_thread' was already set
[2021-11-13T08:33:23-05:00] (und) WARNING: The parameter 'indexer_thread_count' was already set
[2021-11-13T08:33:23-05:00] (und) WARNING: The parameter 'pui_indexer_records_per_thread' was already set
[2021-11-13T08:33:23-05:00] (und) WARNING: The parameter 'pui_indexer_thread_count' was already set
[2021-11-13T08:33:24-05:00] (und) Nov 13, 2021 8:33:24 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
[2021-11-13T08:33:24-05:00] (und) INFO: An exception happened during JRuby-Rack startup
[2021-11-13T08:33:24-05:00] (und) You have requested:
[2021-11-13T08:33:24-05:00] (und)   addressable = 2.8.0
[2021-11-13T08:33:24-05:00] (und) The bundle currently has addressable locked at 2.7.0.
[2021-11-13T08:33:24-05:00] (und) Try running `bundle update addressable`
[2021-11-13T08:33:24-05:00] (und) If you are updating multiple gems in your Gemfile at once,
[2021-11-13T08:33:24-05:00] (und) try passing them all to `bundle update`
[2021-11-13T08:33:24-05:00] (und) --- System
[2021-11-13T08:33:24-05:00] (und) jruby 9.2.12.0 (2.5.7) 2020-07-01 db01a49ba6 OpenJDK 64-Bit Server VM 25.272-b10 on 1.8.0_272-8u272-b10-0ubuntu1~18.04-b10 +jit [linux-x86_64]
[2021-11-13T08:33:24-05:00] (und) Time: 2021-11-13 08:33:24 -0500
[2021-11-13T08:33:24-05:00] (und) Server: jetty/8.1.5.v20120716
[2021-11-13T08:33:24-05:00] (und) jruby.home: uri:classloader://META-INF/jruby.home
[2021-11-13T08:33:24-05:00] (und) --- Context Init Parameters:
[2021-11-13T08:33:24-05:00] (und) jruby.max.runtimes = 1
[2021-11-13T08:33:24-05:00] (und) jruby.min.runtimes = 1
[2021-11-13T08:33:24-05:00] (und) public.root = /
[2021-11-13T08:33:24-05:00] (und) rails.env = production
[2021-11-13T08:33:24-05:00] (und) --- Backtrace
[2021-11-13T08:33:24-05:00] (und) Bundler::GemNotFound: You have requested:
[2021-11-13T08:33:24-05:00] (und)   addressable = 2.8.0
[2021-11-13T08:33:24-05:00] (und) The bundle currently has addressable locked at 2.7.0.
[2021-11-13T08:33:24-05:00] (und) Try running `bundle update addressable`
[2021-11-13T08:33:24-05:00] (und) If you are updating multiple gems in your Gemfile at once,
[2021-11-13T08:33:24-05:00] (und) try passing them all to `bundle update`
[2021-11-13T08:33:24-05:00] (und)   verify_gemfile_dependencies_are_found! at /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/resolver.rb:290
[2021-11-13T08:33:24-05:00] (und)                                     each at org/jruby/RubyArray.java:1809
[2021-11-13T08:33:24-05:00] (und)   verify_gemfile_dependencies_are_found! at /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/resolver.rb:258
[2021-11-13T08:33:24-05:00] (und)                                    start at /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/resolver.rb:49
[2021-11-13T08:33:24-05:00] (und)                                  resolve at /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/resolver.rb:22
[2021-11-13T08:33:24-05:00] (und)                                  resolve at /archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:258
111

**Comment by Geoffsc** [comment]
@Blake- this may be a silly question but is this issue resolved if you run `bundle update addressable` as suggested in the stack trace?

**Comment by mark-cooper** [comment]
@Blake- can you delete any `Gemfile.lock` you already have and try again? Or starting with a fresh checkout of the plugin from this branch would also work.

**Comment by mark-cooper** [comment]
Tested. aspace 2.8.1 is not happy with addressable 2.8, so I created a tag for it. I generally prefer to keep gem specifications loose for plugins, so may drop the addressable entry in the future (like: https://github.com/lyrasis/aspace-oauth/pull/23).

**Pull request merged**
